create database txn;
use txn;
select * from txn_windows;
select count(*) from txn_windows;
create view l as select oid,product,state from txn_windows where dat between '01-01-2011' and '01-31-2011';
select count(*) from l;
create view g as select oid,product,state from txn_windows where dat between '07-01-2011' and '07-01-2011';
select count(*) from g;
select category,count(*)as d from txn_windows group by category order by d desc;
select * from txn_windows where category='Outdoor Recreation';
create view cash as select * from txn_windows where method='cash';
select count(*) from cash;
create view credit as select * from txn_windows where method='credit';
select count(*) from credit;
select count(*)from txn_windows where dat between '01-01-2011' and '07-31-2011';
select category,sum(pay_amount)from txn_windows group by category;
select category,max(pay_amount)from txn_windows group by category;
select category,avg(pay_amount)from txn_windows group by category;
select method,sum(pay_amount)from txn_windows group by method;
select category,sum(pay_amount)from txn_windows where category='Indoor Games' group by category;
select state,count(*) from txn_windows group by state;